
m=open("astha1.txt","w")
m.write("DATE-TIME\t\t\t            FOOD EATEN")
n=open("astha2.txt","w")
n.write("DATE-TIME\t\t\t            EXERCISE DONE")
o=open("kabeer1.txt","w")
o.write("DATE-TIME\t\t\t            FOOD EATEN")
p=open("kabeer2.txt","w")
p.write("DATE-TIME\t\t\t            EXERCISE DONE")
q=open("prakhar1.txt","w")
q.write("DATE-TIME\t\t\t            FOOD EATEN")
r=open("prakhar2.txt","w")
r.write("DATE-TIME\t\t\t            EXERCISE DONE")
